algoritmo "semnome"
// Função :
// Autor :
// Data : 04/04/2022
// Seção de Declarações 
var
   contador, numero, soma: inteiro
inicio
      contador <- 1
      numero <- 0
      enquanto (contador <= 5) faca
      escreva ("Digite o ", contador, " número: ")
      leia (numero)
      soma <- soma + numero
      contador <- contador + 1
      fimEnquanto
			escreval ("A soma dos valores foi de: ",soma)
fimalgoritmo
