algoritmo "aprovação ou reprovação"
// Função :
// Autor :
// Data : 30/03/2022
// Seção de Declarações 
var
   n1, n2, m: real
inicio
      escreva ("Qual foi a sua primeira nota? ")
      leia (n1)
      escreva ("Qual foi a sua segunda nota? ")
      leia (n2)
      m <- (n1 + n2) / 2)
      escreva ("Sua média foi de", m," pontos.")
      se (m >= 6) entao
         escreva (" Você está aprovado!")
      senao
         escreva (" Você reprovou!")
      fimSe
fimalgoritmo
